# Have a ton of different dictionaries describing specific situations that people may be in. 
# They can check them, and it will throw them into the mix. 

vocab1 = {
	"ciao":"hi, bye",
	"salve":"hello",
	"buongiorno":"good morning, good day",
	"buonasera":"good evening",
	"buonanotte":"good night (leaving)",
	"(tanto) piacere":"(so) nice to meet you",
	"molto lieto":"very pleased to meet you",
	"scusa":"excuse me (informal)",
	"scusi":"excuse me (formal)",
	"come ti chiami?":"what is your name? (i)",
	"come si chiama?":"what is your name? (f)",
	"mi chiamo":"my name is",
	"e tu?":"and you? (i)",
	"e Lei?":"and you? (f)",
	"di dove sei?":"where are you from? (i)",
	"di dov'e Lei?":"where are you from? (f)",
	"sono di...":"i am from...",
	"dov'e...?":"where is...?",
	"ecco...":"here is...",
	"come stai?":"how are you? (i)",
	"come sta?":"how are you? (f)",
	"come va?":"how's it going?",
	"sto...":"i'm...",
	"bene":"fine",
	"benissimo":"very well",
	"molto bene":"very well",
	"abbastanza bene":"quite well",
	"cosi-cosi":"so-so",
	"male":"bad",
	"non sto bene":"I'm not well",
	"non c'e male":"not to bad",
	"bene, grazie, e tu?":"fine, thank you, and you? (i)",
	"bene, grazie, e Lei?":"fine, thank you, and you? (f)",
}
vocab1 = dict (zip(vocab1.values(), vocab1.keys()))

alphabet = {
	"a":"ah",
	"b":"bi",
	"c":"chi",
	"d":"di",
	"e":"eh",
	"f":"effe",
	"h":"acca",
	"i":"ee",
	"l":"elle",
	"m":"emme",
	"n":"enne",
	"o":"oh",
	"p":"pi",
	"q":"coo",
	"r":"erre",
	"s":"esse",
	"t":"ti",
	"u":"oo",
	"v":"vu",
	"z":"zeta",
	"j":"i lunga",
	"w":"doble vu",
	"k":"kappa",
	"y":"ipsilon"
}
numbers = {
	0:"zero",
	1:"uno",
	2:"duo",
	3:"tre",
	4:"cuatro",
	5:"cinque",
	6:"sei",
	7:"sette",
	8:"otto",
	9:"nove",
	10:"dieci",
	11:"undici",
	12:"dodici",
	13:"tredici",
	14:"catordici",
	15:"quindici",
	16:"seidici",
	17:"dicisette",
	18:"diciotto",
	19:"dicinove",
	20:"venti"
}
venice_vocab = {
	"type":"tipo",
	"fire":"fuoco",
	"number":"numero",
	"no":"non",
	"dog":"cave",
	"monkey":"scimmia",
	"equal":"eguale",
	"identical":"identici",
	"photocopy":"fotocopia",
	"no one":"nessuno",
	"map":"mappa",
	"croissant":"cornetto",
	"glass":"vetro",
	"drinking glass":"bicchiere",
	"flower":"fiore",
	"horse":"cavallo",
	"water":"acqua",
	"square":"campo",
	"student":"studente",
	"airplane":"aereo",
	"tree":"albero",
	"bus":"autobus",
	"bar":"bar",
	"boat":"barca",
	"bottle":"bottiglia",
	"coffee":"caffe",
	"road/street":"calle",
	"canal":"canale",
	"church":"chiesa",
	"park":"giardino",
	"island":"isola",
	"plaza":"piazza",
	"bridge":"ponte",
	"steps":"scalino",
	"beach":"spiaggia",
	"station":"stazione",
	"train":"treno",
	"tourist (m + f)":"turista",
	"guide (m + f)" : "guida",
	"backpack":"zaino",
	"gym":"palestra"
	}

vocab3 = {
	"i'm hungry":"ho fame",
	"it is hot":"ha caldo",
	"he is sleepy":"lui ha sonno",
	"i'm late/in a hurry":"ho fretta",
	"thirst":"sete",
	"it is cold":"ha freddo",
	"i'm not afraid":"non ho paura",
	"he is happy":"lui e felice",
	"she is content":"lei e contenta",
	"i am sad":"sono triste",
	"they are bored":"sono annoiato",
	"are you annoyed? (f)":"Lei e arrabbiato?",
	"tired":"stanco",
	"he is despaired":"lui e disparato",
	"she is crazy":"lei e pazza",
	"i'm rich":"sono rica",
	"i'm poor":"sono povero",
	
}
data = {
	
	"the day":"il giorno",
	"the week":"la settimana",
	"today":"oggi",
	"tomorrow":"domani",
	"yesterday":"ieri",
	"day before yesterday":"l'altro ieri",
	"day after tomorrow":"dopodomani",
	"the weekend":"il fine settimana",
	"the morning":"il mattino",
	"the afternoon":"il pomeriggio",
	"the evening":"la sera",
	"the night":"la notte",	
	"the time, weather":"il tempi",
	"the program/plan":"il programma",
	"last":"ultimo",
	"what day is it today?":"che giorno e oggi?",
	"what is the date?":"qual e la data?",
	"today is september 24th":"oggi e il 24 settembre",
	"my birthday is july 17th":"il mio compleanno e il 17 luglio",
	"i have italian class mondays, wednesdays, and fridays":"ho lezione d'italiano il lunedi, il mercoledi, e il vernerdi",
	"i go to church every sunday":"vado in chiesa la domenica",
	
}
lezione = {
	
	"the class":"la classe",
	"the lesson":"la lezione",
	"the course":"il corso",
	"the homework":"il compito",
	"the desk":"la scrivania",
	"to attend (a school)":"frequentare",
	"to take a course":"seguire un corso",
	"to teach":"insegnare",
	"to learn":"imparare",
	"to take notes":"prendere appunti",
	"to make a mistake":"sbagliare",
	"correct":"corretto",
	"incorrect":"sbagliato",
	"i don't know":"non lo so"
	
}
vocab4 = {
	"boot": "il stivale",
	"volcano":"il vulcano",
	"the region":"la regione",
	"the river":"il fiume",
	"the city":"la citta",
	"the conversation":"la conversazione",
	"the opinion":"il opinione",
	"the sport":"il sport",
	"the university":"la universita",
	"the pizzeria is in san marco":"la pizzeria e in san marco",
	"i live in venice":"io abito a venezia",
	"where are you from (i)?":"di dove sei?",
	"i am speaking with giovanni":"parlo con giovanni",
	"there are many monuments in Italy":"ci sono molti monumenti in Italia",
	"for me, Rome is the Colosseum":"per me, Roma e il Colosseo",
	"far from":"lontano da",
	"in front of":"davanti a",
	"near":"vicinto a",
	"behind":"dietro a",

}

azione = {
	"to eat a pizza":"mangiare una pizza",
	"to drink a spritz":"bere uno spritz",
	"to do homework":"fare i compiti",
	"to sleep":"dormire",
	"to dance in a club":"ballare in discoteca",
	"to run in the park":"correre al parco",
	"to talk with a friend":"parlare con un amico",
	"to sing a song":"cantare una canzione",
	"to read a book":"leggere un libro",
	"to play cards":"giocare a carte",
	"to close the door":"chiudere la porta",
	"to open the window":"aprire la finestra",
	"to talk":"parlare",
	"to dance":"ballare",
	"to sing":"cantare",
	"to play":"giocare",
	"to run":"correre",
	"to close":"chiudere",
	"to sleep":"dormire",
	"to chat":"chattare",
	"to use":"usare",
	"what do you do in your free time?":"cosa fai nel tempo libero?",
	"just kidding":"scherzo",
	"the pot":"la pentola",
	"the shoes":"le scarpe",
	"the table":"il tavolo",
	"the suitcase":"la valigia"
}
utiles = {
	"when":"quando",
	"what":"che",
	"why":"per che",
	"for":"per",
	"how much":"quanto",
	"how many (plural)": "quanti",
	"everything good":"tutto bene",
	"what's up":"come va",
	"what time is it?":"che ora e?",
	"a thousand thanks":"grazie mille",
	"also":"anche",
	"normally":"di solito",
	"on the contrary":"invece",
	"in":"nel",
	"who,whom":"chi",
	"what":"che/cosa",
	"which (singular)":"quale",
	"how":"come",
	"where":"dove",
	"why":"perche",
	"which (plural)":"quali",
	"how come":"come mai",
	"this":"questo"

}

mesi = {
	"january":"gennaio",
	"february":"febbraio",
	"march":"marzo",
	"april":"aprile",
	"may":"maggio",
	"june":"giugno",
	"july":"luglio",
	"august":"agosto",
	"september":"settembre",
	"october":"ottobre",
	"november":"novembre",
	"december":"dicembre",
}
famiglia = {
	"sister":"sorella",
	"brother":"fratello",
	"mother":"madre",
	"father":"papa",
	"aunt":"zia",
	"uncle":"zio",
	"grandmother":"nonna",
	"grandfather":"nonno",
	"cousin":"cugino",
	"son":"figlio",
	"daughter":"figlia"
}
colori = {
	"cyan":"azzurro",
	"white":"bianco",
	"black":"nero",
	"grey":"grigio",
	"red":"rosso",
	"yellow":"giallo",
	"blue":"blu",
	"violet":"viola",
	"pink":"rosa",
	"green":"verde",
	"brown":"marrone",
	"orange":"arancione"
}
clothes = {
	"robe":"accappatio",
	"socks":"calzini",
	"boots":"stivali",
	"sweater":"maglione",
	"waterproof":"impermeabile",
	"coat":"cappotto",
	"pants":"pantaloni",
	"heels":"scarpe con il tacco",
	"jacket":"giacca",
	"rain jacket":"giacca a vento",
	"bathing suit":"costume de bagno",
	"dress":"gonna",
	"shorts":"pantaloncini",
	"sunglasses":"occhiali da sole",
	"gloves":"guanti",
	"pajama":"pigiama",
	"portfolio":"portafoglio",
	"hat":"cappello",
	"wedding dress":"vestito da sposa",
	"belt":"cintura",
	"scarf":"sciarpa",
	"slippers":"pantafole",
	"necklace":"collana",
	"tie":"cravatta",

}
spiaggia = {
	"the sunscreen":"la crema solare",
	"the flip flops":"le ciabatte",
	"the big umbrella":"l'ombrellone",
	"the beach towel":"il telo da mare",
	"the towel":"l'ascugiamano",
	"the seat":"la sedia",
}
alimenti = {
	"milk":"latte",
	"butter":"burro",
	"rice":"riso",
	"sugar":"zucchero",
	"vinegar":"aceto",
	"bread":"pane",
	"oil":"olio",
	"egg":"uova",
	"fish":"pesce",
	"salt":"sale",
	"cheese":"formaggio",
	"watermelon":"cocomero",
	"apple":"mela",
	"strawberry":"fragola",
	"cherry":"ciliegia",
	"apricot":"albicocca",
	"grape":"uva",
	"tomato":"pomodoro",
	"mushroom":"fungo",
	"pumpkin":"zucca",
	"pepper":"peperone",
	"onion":"cipolla",
	"garlic":"aglio",
	"potato":"patata",
	"eggplant":"melanzana",
	"gram":"grammo",
	"kilogram":"chilo",
	"liter":"litro"

}
ristorante = {
	"potatoes":"patate",
	"artichoke":"carciofi",
	"spinach":"spinaci",
	"mussels":"vongole",
	"turkey":"tacchino",
	"too":"troppo",

}
fisico = {
	"blonde":"biondo",
	"brunette":"castana",
	"short (height)":"basso",
	"tall (height)":"alto",
	"small (weight)":"piccolo",
	"fat":"grasso",
	"curly hair":"capelli risci",
	"short hair":"capelli corti",
	"long hair":"capelli lungi",
	"straight hair":"capelli lisci",
	"bald":"calvo",
	"beard":"barba",
	"moustache":"baffi"

}
derp = {
	"":"",
	"":"",
	"":"",
	"":"",
	"":"",
	"":"",
	"":"",
	"":"",
	"":"",
	"":"",
	"":"",
	"":"",

}

# GET ALL THE VERBS
from verbs import tipos
verbi = {}
for x in tipos:
	# get all the values
	y = x.values()
	z = []
	for a in y:
		z.append("to " + a)
	verbi.update(dict(zip(z, x.keys())))
# put back in vocab 1 and venice_vocab after you learn these
# all_vocab = [vocab3, data, lezione, vocab4]
# all_vocab = [azione, utiles, mesi, famiglia, colori, alimenti, clothes, verbi, spiaggia, ristorante, fisico, alimenti]
all_vocab = [vocab1, venice_vocab, vocab3, data, lezione, vocab4, azione, utiles, mesi, famiglia, colori, clothes, spiaggia, alimenti, ristorante, fisico]